fix: build for both jazzy and kilted

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,6 +10,16 @@ on:
           - ""
           - foxglove_bridge
 
+      build_kilted:
+        type: boolean
+        default: true
+        description: "Release for Kilted"
+
+      build_jazzy:
+        type: boolean
+        default: true
+        description: "Release for Jazzy"
+
 jobs:
   setup:
     runs-on: ubuntu-latest
@@ -18,18 +28,14 @@ jobs:
     steps:
       - id: set-distros
         run: |
-          case "${{ github.ref_name }}" in
-            jazzy)
-              distros=("jazzy")
-              ;;
-            main)
-              distros=("kilted")
-              ;;
-            *)
-              echo "::error::Unsupported branch '${{ github.ref_name }}'. Releases can only be made from 'main' (kilted) or 'jazzy' branches."
-              exit 1
-              ;;
-          esac
+          distros=()
+          [ "${{ github.event.inputs.build_jazzy }}" == "true" ] && distros+=("jazzy")
+          [ "${{ github.event.inputs.build_kilted }}" == "true" ] && distros+=("kilted")
+
+          if [ ${#distros[@]} -eq 0 ]; then
+            echo "::error::No distros selected. Please enable release for at least one of the available distros."
+            exit 1
+          fi
 
           echo "distros=$(jq -cn '$ARGS.positional' --args "${distros[@]}")" >> $GITHUB_OUTPUT
 
